### ISSUE TITLE
Namespaced keywords for components names

### ISSUE THREAD

**Issue by Otann** [roman01la/scrum#2]
Hi!

I am trying to use namespaced keywords to bring more clarity to subscribing and dispatching and could not make it work.

Here is a modified example of a component:

```clojure
(ns probe.scrum.counter
  (:require [rum.core :as rum]
            [scrum.core :as scrum]))

(rum/defc counter-ui < rum/reactive [r]
  [:div
   ; :counter here should be in sync with keyword in
   ; reconciler declaration -> =(
   [:button {:on-click #(scrum/dispatch! r ::state :dec)} "-"]
   [:span   (rum/react (scrum/subscription r [::state]))]
   [:button {:on-click #(scrum/dispatch! r ::state :inc)} "+"]])

(def initial-state 0)

(defmulti counter-controller (fn [action] action))
(defmethod counter-controller :init [] initial-state)
(defmethod counter-controller :inc [_ _ counter] (inc counter))
(defmethod counter-controller :dec [_ _ counter] (dec counter))
```

And here is `core.clj`

```clojure
(ns probe.core
  (:require [rum.core :as r]
            [scrum.core :as scrum]
            [probe.scrum.counter :as counter]))

(defonce reconciler
  (scrum/reconciler {:state       (atom {})
                     :controllers {:counter/state counter/counter-controller}}))
(defonce init-ctrl
  (scrum/broadcast-sync! reconciler :init))

(r/mount (counter/counter-ui reconciler)
         (js/document.getElementById "app"))
```

Could you please help me understand is it a bug or am I doing something wrong here?

**Comment by DjebbZ** [comment]
Stumbled on the same exact problem today. It has nothing to do with scrum/rum but pure Clojure. When using namespaced keyword the keyword gets the current namespace. In your first code snippet `::state` would become `:probe.scrum.counter/state`, whereas in the 2nd code snippet you're using `:counter/state`. They don't match, so you don't get the controller and nothing works.

Read more at the official docs : https://clojure.org/reference/reader#_literals

**Comment by roman01la** [comment]
@Otann Hi. I guess the problem is that you might need to use the keyword like this
```clj
::counter/state
```
Notice here it is fully qualified keyword and because you have already imported ns `probe.scrum.counter` as `counter` it means that `counter` symbols becomes ns alias in `::counter/state` keyword which really means `:probe.scrum.counter/state`

**Comment by Otann** [comment]
You guys are absolutely right, I forgot the second colon!
