### ISSUE TITLE
Best practice regarding reconciler

### ISSUE THREAD

**Issue by DjebbZ** [roman01la/scrum#5]
Simple question : for non-trivial application with deep tree of components, how do you pass the reconciler down ? Top down from parents to children ? Require it where necessary ?

I'm interested in your personal experience.

**Comment by roman01la** [comment]
I prefer passing it explicitly. Since it is reference type it won't affect `shouldComponentUpdate` aka `rum/static` optimization. But if you prefer to do it Redux-way, you can use context in Rum as well https://github.com/tonsky/rum/#interop-with-react

**Comment by DjebbZ** [comment]
> I prefer passing it explicitly

I think I'll go this way, boilerplate is small.

> This should be documented probably.

Agree. I'll write a PR now.

**Comment by DjebbZ** [comment]
See #4
