### ISSUE TITLE
Proposal: Effects handling

### ISSUE THREAD

**Issue by roman01la** [roman01la/scrum#7]
This is the first draft that describes possible approach to effects handling in Scrum, inspired by re-frame. Code example is available in [this gist](https://gist.github.com/roman01la/d4e5acc08fb5b455438fe84255933ab0).

## Controllers

A controller returns description of a side-effects as data. `:state` is a built-in effects handler.

Side-effects description should follow these rules:
- description is a hash map
- a key is an identifier of a particular effect handler (`:state`, `:http`, etc.)
- a value is a value which satisfies particular effect handler

```clj
(defmethod control :inc [_ _ state]
  {:state (update state :count inc)
   :http {:method :put
          :uri "/api/count"
          :data (inc (:count state))
          :on-success :inc-ready
          :on-fail :inc-fail}})
```

## Reconciler

New key `:effects` is added. The value is a hash map from effect handler identifier to handler function.

```clj
(def r
  (scrum/reconciler
    {:state (atom {})
     :controllers {:counter counter/control}}
     :effects {:http effects/http}))
```

## Effect handlers

Effect handler is a function that receives...
- an instance of `Reconciler`
- controller identifier
- effect description returned by controller

```clj
(defn http [reconciler controller {:keys [method uri data on-success on-fail]}]
  (-> (httpurr/get uri {:method method :data data})
        (p/then #(scrum/dispatch! reconciler controller on-success %))
        (p/catch #(scrum/dispatch! reconciler controller on-fail %))))
```

## Execution flow
- Dispatch an event `(scrum/dispatch! r :user :load user-id)`
- Triggered controller returns effect description `{:http {...}}`
- Reconciler executes appropriate effects handler passing in itself, controller name and effect value
- Once effect performed it may dispatch (server response, etc.)

## Advantages
- Сonvenient async effects handling (no need to pass reconciler instance into controller to dispatch response later)
- Pluggable & reusable effect handlers

**Comment by roman01la** [comment]
Published first implementation as `2.1.0-SNAPSHOT`

**Comment by roman01la** [comment]
@DjebbZ I'll answer to [your comment](https://gist.github.com/roman01la/d4e5acc08fb5b455438fe84255933ab0#gistcomment-2077887) here.

> Line 18 why not simply return response ? In this proposal, the control controller isn't responsible directly for the state at the key :counter ? What is the value of the state parameter in the controller methods ?

It's an implementation details of particular effects handler. For example if effects handler returns response body and this object represents the entire state of a controller then it's fine to replace the whole state with response object. But most of the time you fetch some data that should be stored at some key in the state. That's why we need original state, so we can assoc a new value into it.

**Comment by roman01la** [comment]
Just published an update to `2.1.0-SNAPSHOT` and up to date documentation, see 
 https://github.com/roman01la/scrum#side-effects

**Comment by DjebbZ** [comment]
First, I'm very happy that you document everything so cleanly. This is how open-source succeeds :+1: 

Second, I still have the same problem with controllers. In the new docs, section [Handling Events](https://github.com/roman01la/scrum#handling-events), for the `:init` event you return only the relevant part of the state, but for the other you return a complete (and updated) state map (`(update state :counter inc)`). Furthermore, in the [Testing](https://github.com/roman01la/scrum#testing) section the counter controller always return only part of the state (`(inc counter)`).

I feel like I'm missing something. I understand your previous comment, indeed having the whole state available in controllers is helpful and necessary to manage the various complexities in real apps and state modeling.

BTW : effects as data is really nice, as it allows easy testing (as shown in readme) and in general is the good trend in front-end frameworks. Keep up the good work.
BTW2: Haven't read the new code yet. Will do !

**Comment by roman01la** [comment]
@DjebbZ Thanks!

You are right. In _Handling events_ section `initial-state` value is incorrect, it should be `{:counter 0}`. I've updated it to match the code in _Testing_ section.

**Comment by DjebbZ** [comment]
Everything is clear now. Cool !

Will read the new code soon.

**Comment by DjebbZ** [comment]
In the readme :

> NOTE: :state is the only handler built into Scrum, because state change is always required operation.

Does it mean handlers **must** return a map with the `:state` key ?

**Comment by roman01la** [comment]
No, it's totally fine to return any other effect or no effects at all

**Comment by roman01la** [comment]
This note should be less confusing

**Comment by DjebbZ** [comment]
Maybe say instead "because Scrum is a state manager. Side effects are application-specific so Scrum only provides a sane architecture to deal with them."

Inspiration from the train 😉

**Comment by roman01la** [comment]
@DjebbZ done!
